export enum UserRole {
  SUPER_ADMIN = 'super_admin',
  SUPERVISOR = 'supervisor',
  ENUMERATOR = 'enumerator',
  DATA_ENTRY_CLERK = 'data_entry_clerk',
  VERIFICATION_ASSESSOR = 'verification_assessor',
  GOVERNMENT_OFFICIAL = 'government_official',
  PUBLIC_USER = 'public_user',
}

// assessorResolutionTypes removed — canonical source is assessorResolutions in fraud.ts
// Drizzle schema file (fraud-detections.ts) has its own local copy per the Drizzle pattern.

export enum Lga {
  AFIJIO = 'afijio',
  AKINYELE = 'akinyele',
  ATIBA = 'atiba',
  ATISBO = 'atisbo',
  EGBEDA = 'egbeda',
  IBADAN_NORTH = 'ibadan_north',
  IBADAN_NORTH_EAST = 'ibadan_north_east',
  IBADAN_NORTH_WEST = 'ibadan_north_west',
  IBADAN_SOUTH_EAST = 'ibadan_south_east',
  IBADAN_SOUTH_WEST = 'ibadan_south_west',
  IBARAPA_CENTRAL = 'ibarapa_central',
  IBARAPA_EAST = 'ibarapa_east',
  IBARAPA_NORTH = 'ibarapa_north',
  IDO = 'ido',
  IREPO = 'irepo',
  ISEYIN = 'iseyin',
  ITESIWAJU = 'itesiwaju',
  IWAJOWA = 'iwajowa',
  KAJOLA = 'kajola',
  LAGELU = 'lagelu',
  OGBOMOSHO_NORTH = 'ogbomosho_north',
  OGBOMOSHO_SOUTH = 'ogbomosho_south',
  OGO_OLUWA = 'ogo_oluwa',
  OLORUNSOGO = 'olorunsogo',
  OLUYOLE = 'oluyole',
  ONA_ARA = 'ona_ara',
  ORELOPE = 'orelope',
  ORI_IRE = 'ori_ire',
  OYO_EAST = 'oyo_east',
  OYO_WEST = 'oyo_west',
  SAKI_EAST = 'saki_east',
  SAKI_WEST = 'saki_west',
  SURULERE = 'surulere',
}
