/**
 * Comprehensive Nigerian banks list organized by category
 * Source: CBN Licensed Financial Institutions (2024)
 *
 * Shared between activation wizard (BankDetailsStep) and profile edit (ProfileEditForm).
 */
export const BANK_CATEGORIES = {
  'Commercial Banks': [
    'Access Bank Plc',
    'Citibank Nigeria Ltd',
    'Ecobank Nigeria Plc',
    'Fidelity Bank Plc',
    'First Bank of Nigeria Ltd',
    'First City Monument Bank (FCMB) Plc',
    'Globus Bank Ltd',
    'Guaranty Trust Bank (GTBank) Plc',
    'Keystone Bank Ltd',
    'Polaris Bank Ltd',
    'Premium Trust Bank Ltd',
    'Providus Bank Ltd',
    'Stanbic IBTC Bank Plc',
    'Standard Chartered Bank Nigeria Ltd',
    'Sterling Bank Plc',
    'SunTrust Bank Nigeria Ltd',
    'Titan Trust Bank Ltd',
    'Union Bank of Nigeria Plc',
    'United Bank for Africa (UBA) Plc',
    'Unity Bank Plc',
    'Wema Bank Plc',
    'Zenith Bank Plc',
    'Optimus Bank Ltd',
    'Parallex Bank Ltd',
    'Signature Bank Ltd',
  ],
  'Non-Interest (Islamic) Banks': [
    'Jaiz Bank Plc',
    'TAJBank Ltd',
    'Lotus Bank Ltd',
    'Alternative Bank Ltd',
  ],
  'Digital & Microfinance Banks': [
    'Kuda Microfinance Bank',
    'OPay (OPay MFB)',
    'PalmPay (PalmPay MFB)',
    'Moniepoint MFB',
    'Carbon MFB',
    'FairMoney MFB',
    'Renmoney MFB',
    'Sparkle MFB',
    'VFD Microfinance Bank',
    'ALAT by Wema',
    'Rubies Bank',
    'Eyowo MFB',
    'LAPO Microfinance Bank',
    'Accion Microfinance Bank',
    'AB Microfinance Bank',
    'NPF Microfinance Bank',
    'Grooming Microfinance Bank',
    'Baobab Microfinance Bank',
    'FCMB Microfinance Bank',
    'Mutual Trust Microfinance Bank',
    'Fina Trust Microfinance Bank',
    'Page Microfinance Bank',
    'Nirsal Microfinance Bank',
    'Mainstreet Microfinance Bank',
    'Seed Capital Microfinance Bank',
    'Fortis Microfinance Bank',
    'Infinity Microfinance Bank',
    'Trustfund Microfinance Bank',
    'Peace Microfinance Bank',
  ],
  'Payment Service Banks': [
    'MoMo Payment Service Bank (MTN)',
    '9 Payment Service Bank (9PSB)',
    'Hope Payment Service Bank',
    'Money Master PSB',
    'Smartcash PSB (Airtel)',
  ],
} as const;

export const ALL_BANKS: readonly string[] = Object.values(BANK_CATEGORIES).flat();
